[package]
name = "sasbackend_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = "0.15.1"
rust_decimal = "1.35.0"
rust_decimal_macros = "1.34.2"
salvo = "0.68.0"
serde = "1.0.203"
surrealdb = "1.5.1"
tokio = "1.38.0"
tokyo = "1.0.0"
tracing-subscriber = "0.3.18"
